/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  /*mySidebar: [
    {
      type: 'doc', 
      id: 'intro',
      label: '👋 Welcome'
    },
    {
      items: [
        'core-blockchain', 
        {
          type: 'category',
          label: 'Core Blockchain',
          items: ['consensus', 'governance', 'pallets', 'security']
        },
      ],
    },

],*/

  };


module.exports = sidebars;
